spring:
  application:
    name: Samvaad-Care
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.default_schema: samvaadcare
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: User Management
        url: /doc/v3/user-api
      - name: Payment Management
        url: /doc/v3/payment-api
    display-request-duration: true
    doc-expansion: none
security:
  cors:
    mappings:
      - path: /**
        allowed-origins: ${CORS_ALLOWED_ORIGINS}
        allowed-methods:
          - "*"
        allow-credentials: false
  public-access:
    - /swagger-ui.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /doc/v3/**
